.\" 	$calcurse: calcurse.1,v 1.12 2008/12/09 21:09:17 culot Exp $
.\"
.\" Copyright (c) 2004-2008 Frederic Culot
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330,
.\" Boston, MA 02111-1307, USA.
.\"
.fam C
.TH CALCURSE 1 "December 09, 2008" "Version 2.4" "Calcurse Manual"
.SH NAME
Calcurse \- text-based organizer
.SH SYNOPSIS
.B "calcurse "
[\fB-h\fP|\fB-v\fP] [\fB-N\fP] [\fB-an\fP] [\fB-t\fP[\fInum\fP]]
[\fB-c\fP<\fIfile\fP> | \fB-D\fP<\fIdir\fP>]
.br
         [\fB-i\fP<\fIfile\fP>] [\fB-x\fP[\fIformat\fP]]
[\fB-d\fP <\fIdate\fP>|<\fInum\fP>]
.br
         [\fB-s\fP[\fIdate\fP]] [\fB-r\fP[\fIrange\fP]]
.br
         
.SH DESCRIPTION
Calcurse is a text-based calendar and scheduling application. It helps
keeping track of events, appointments and everyday tasks. 
A configurable notification system reminds user of upcoming deadlines,
and the curses based interface can be customized to suit user needs.
All of the commands are documented within an online help system.  
.SH OPTIONS
The following options are supported:
.TP
\fB-a\fP, \fB--appointment\fP
Print the appointments and events for the current day and exit. 
.br
\fINote:\fP the calendar from which to read the appointments can be specified using
the '\-c' flag. 
.TP
\fB-c\fP <file>, \fB--calendar\fP <file>
Specify the calendar file to use. The default calendar is 
.B "'~/.calcurse/apts'" 
(see section \fIFILES\fP below). This option is incompatible with \fB-D\fP.
.TP
\fB-d\fP <date|num>, \fB--day\fP <date|num>
Print the appointments and events for the given date or for 
the given number of upcoming days, depending on the argument format. 
Two possible formats are supported:
.RS 9
.TP 2
\(bu  a date of the form 'mm/dd/yyyy'. 
.TP 2
\(bu  a number 'n'. 
.RE
.RS 7
.LP
In the first case, the appointments and events list for the specified 
date will be returned, while in the second case the appointments and events 
list for the 'n' upcoming days will be returned. 
.br
As an example, typing 'calcurse -d 3' will display your appointments 
and events for today, tomorrow, and the day after tomorrow.   
.br
\fINote:\fP as for the '-a' flag, the calendar from which to read the 
appointments can be specified using the '\-c' flag. 
.RE
.TP
\fB-D\fP <dir>, \fB--directory\fP <dir>
Specify the data directory to use. This option is incompatible with \fB-c\fP.
If not specified, the default directory is 
.B "'~/.calcurse/'" 
.TP
\fB-h\fP, \fB--help\fP
Print a short help text describing the supported command-line options,
and then exit. 
.TP
\fB-i\fP <file>, \fB--import\fP <file>
Import the icalendar data contained in \fIfile\fP.
.TP
\fB-n\fP, \fB--next\fP
Print the next appointment within upcoming 24 hours and exit.
The indicated time is the number of hours and minutes left before this
appointment.
.br
\fINote:\fP the calendar from which to read the appointments can be specified using
the '\-c' flag.
.TP
\fB-N\fP, \fB--note\fP
When used with the '-a' or '-t' flag, also print note content
if one is associated with the displayed item.
.TP
\fB-r\fP[num], \fB--range\fP[=num]
Print events and appointments for the \fInum\fP number of days
and exit. If no \fInum\fP is given, a range of 1 day is considered.
.TP
\fB-s\fP[date], \fB--startday\fP[=date]
Print events and appointments from \fIdate\fP and exit.
If no \fIdate\fP is given, the current day is considered.
.TP
\fB-t\fP[num], \fB--todo\fP[=num]
Print the 'todo' list and exit. If the optional number \fInum\fP is given,
then only todos having a priority equal to \fInum\fP will be returned.
.br
\fINote:\fP priority number must be between 1 (highest) and 9 (lowest).
.TP
\fB-v\fP, \fB--version\fP
Display calcurse version and exit.
.TP
\fB-x\fP[format], \fB--export\fP[=format]
Export user data to the specified format. Events, appointments and
todos are converted and echoed to stdout. Two possible formats are
available: \fIical\fP and \fIpcal\fP.
If the optional argument format is not given, ical format is
selected by default.
.br
\fINote:\fP redirect standard output to export data to a file,
by issuing a command such as: 
.br
.B    $ calcurse --export > calcurse.dat
.SH NOTES
Calcurse interface contains three different panels (calendar,
appointment list, and todo list) on which you can perform different
actions. All the possible actions, together with their associated
keystrokes, are listed on the status bar. This status bar
takes place at the bottom of the screen.
.PP
At any time, the built-in help system can be invoked by pressing the '?'
key. Once viewing the help screens, informations on a specific command
can be accessed by pressing the keystroke corresponding to that command.
.SH CONFIGURATION
The calcurse options can be changed from the configuration menu (shown
when 'C' is hit). Five possible categories are to be chosen from : the
color scheme, the layout (the location of the three panels on the
screen), notification options, key bindings configuration menu,
and more general options (such as automatic save before quitting). 
All of these options are detailed in the configuration menu.
.SH FILES
The following structure is created in your $HOME directory 
(or in the directory you specified with the \fB-D\fP option),
the first time calcurse is run:
.PP
.HP 10
$HOME/.calcurse/
.br
|___notes/
.br
|___conf 
.br
|___keys
.br
|___apts 
.br
|___todo
.PP
The \fInotes\fP subdirectory contains descriptions of the notes 
which are attached to appointments, events or todos. One text file is
created per note, whose name is built using mkstemp(3) and should be
unique, but with no relation with the corresponding item's description.
.br
The \fIconf\fP file contains the user configuration. The \fIkeys\fP
file contains the user-defined key bindings. The \fIapts\fP 
file contains all of the user's appointments and events, and the 
\fItodo\fP file contains the todo list.
.SH ENVIRONMENT
This section describes the environment variables that affect how
calcurse operates. 
.TP 4
\fBVISUAL\fP 
Specifies the external editor to use for writing notes.
.TP 4
\fBEDITOR\fP
If the \fIVISUAL\fP environment variable is not set, then \fIEDITOR\fP 
will be used as the default external editor. If none of those variables
are set, then \fI/usr/bin/vi\fP is used instead.
.TP 4
\fBPAGER\fP
Specifies the default viewer to be used for reading notes. If this variable
is not set, then \fI/usr/bin/less\fP is used.
.SH BUGS
Incorrect highlighting of items appear when using calcurse black and
white theme together with a \fB$TERM\fP variable set to
\fIxterm-color\fP. 
To fix this bug, and as advised by Thomas E. Dickey (xterm maintainer),
\fIxterm-xfree86\fP should be used instead of \fIxterm-color\fP to set 
the \fB$TERM\fP variable:
    "The xterm-color value for $TERM is a bad choice for 
     XFree86 xterm because it is commonly used for a 
     terminfo entry which happens to not support bce. 
     Use the xterm-xfree86 entry which is distributed 
     with XFree86 xterm (or the similar one distributed 
     with ncurses)."
.PP
If you find other bugs, please send a report to calcurse@culot.org or to the
author, below.
.SH SEE ALSO
vi(1), less(1), ncurses(3), mkstemp(3)
.br
The ical specification (rfc2445) can be found at:
http://tools.ietf.org/html/rfc2445
.br
The pcal project page: http://pcal.sourceforge.net/
.br
Calcurse home page: http://culot.org/calcurse/
.br
Calcurse complete manual, translated in many languages and maintained in
html format, can be found in the doc/ directory of the source package, 
or at: http://culot.org/calcurse/manual.html
.SH AUTHOR
\fBFrederic Culot\fP <frederic@culot.org>.
.SH COPYRIGHT
Copyright (c) 2004-2008 by Frederic Culot. 
.br
This software is released under the GNU General Public License. Please
read the COPYING file for more information. 
